name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint 
        run: |
          make lint

      - name: Format
        run: |
          make format

      - name: Login to Github Container Registry
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t docker.io/smokepaus/flask-app:latest .
          
      - name: Push Docker image to Registry
        run: |
          docker push docker.io/smokepaus/flask-app:latest

      - name: Docker build app, run it, and check if server responds.
        run: |
          docker build -t flask-app .
          docker run -d -p 5000:5000 flask-app
          sleep 3 # wait for the server to start
          curl -I http://localhost:5000  # check if the server responds

